server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eticket
    username: postgres
    password: 690
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true
  sql:
    init:
#      mode: always
      mode: never

basket:
  live-time: 60000

jwt:
  secret-key: nimakerakshusuzjasndjandoasndasndiasndasndkasndkasdnsaldlaskdn
  expire:
    access_token: 604800000
#    access_token: 10000
    refresh_token: 1728000000

verification-code:
  expire-time: 10800000
  limit: 5

twilio:
  account_sid: AC12f709df4c3da648649a6343133dfa85
  auth_token: 495e000c0e030a216fa823bb2404a28e
  phone_number: +19404129516

stripe:
  secret-key: sk_test_51JkAobLKO4a53BDZfp9GpkCGpBqM2an5RW9zDpbJcCbCpZCIcBf5wdD44Cnkq8KiBMkbqG7gy7DAw1DY07rS7tVb00g7927C5M




